# Enable the "Sponsor" button by uncommenting and filling in the platforms you use.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# github: [chrreiter]
# ko_fi: your-handle
# buy_me_a_coffee: your-handle
# custom: ["https://example.com/donate"]
