from collections.abc import Callable
from typing import Any

from homeassistant.core import HomeAssistant

class ActiveConnection:
    # Values are invoked by HA when the connection closes.
    subscriptions: dict[Any, Callable[[], Any]]
    def send_message(self, message: dict[str, Any]) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    # Note: the real class defines __slots__; writes to unknown attributes can
    # raise at runtime and must stay guarded (see ws._register_close_listener).
    def __setattr__(self, name: str, value: Any) -> None: ...

def websocket_command[F: Callable[..., Any]](schema: dict[Any, Any]) -> Callable[[F], F]: ...
def async_response[F: Callable[..., Any]](func: F) -> F: ...
def result_message(iden: int, result: Any = ...) -> dict[str, Any]: ...
def error_message(
    iden: int | None,
    code: str,
    message: str,
    translation_key: str | None = ...,
    translation_domain: str | None = ...,
    translation_placeholders: dict[str, Any] | None = ...,
) -> dict[str, Any]: ...
def async_register_command(hass: HomeAssistant, handler: Any) -> None: ...
def __getattr__(name: str) -> Any: ...
