add_item:
  name: Add item
  description: Add a new inventory item
  fields:
    name:
      required: true
      example: "Hammer"
      selector:
        text:
    quantity:
      required: false
      example: 1
      selector:
        number:

check_out_item:
  name: Check out item
  description: Mark an item as checked out with an optional due date
  fields:
    item_id:
      required: true
      example: "uuid-of-item"
      selector:
        text:
    due_date:
      required: false
      example: "2025-01-01"
      selector:
        date:
