#!/usr/bin/env bash
# Regenerate requirements-dev.txt from pyproject.toml + uv.lock.
#
# The export is the pip-installable copy of the locked dev group, used by the
# recipes in .claude/skills/ and as the fallback in .claude/hooks/session-start.sh.
# Every pin is derived from uv.lock, never edited by hand;
# tests/test_toolchain_pins.py fails while the two disagree.
#
# uv's own header names the command and output path it was run with, so it is
# replaced with a fixed one that does not change per author.
source "$(dirname "$0")/common.sh"

if [ -z "${UV:-}" ]; then
  err 'uv not found. Install it: https://docs.astral.sh/uv/getting-started/installation/'
  exit 1
fi

OUT="$REPO_ROOT/requirements-dev.txt"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

info 'Exporting the dev group from uv.lock...'
{
  cat <<'HEADER'
# GENERATED by `uv export --only-group dev` — do not edit by hand.
# Source of truth: pyproject.toml [dependency-groups] + uv.lock.
# Regenerate: bash scripts/export_dev_requirements.sh
# Kept as a pip-compatible fallback for environments without uv.
HEADER
  # The body starts at the first column-1 line that is not a `#` comment
  # (`# via` annotations are indented).
  "$UV" export --only-group dev --no-hashes --no-emit-project \
    | awk 'body || !/^#/ { body = 1; print }'
} >"$TMP"

# mktemp writes 0600.
chmod 0644 "$TMP"
mv "$TMP" "$OUT"
ok "Wrote ${OUT#"$REPO_ROOT/"}"
