from typing import Any

from homeassistant.core import HomeAssistant

def add_extra_js_url(hass: HomeAssistant, url: str) -> None: ...
def remove_extra_js_url(hass: HomeAssistant, url: str) -> None: ...
def __getattr__(name: str) -> Any: ...
