from typing import Any

from homeassistant.core import HomeAssistant

def add_extra_js_url(hass: HomeAssistant, url: str, es5: bool = ...) -> None: ...
def remove_extra_js_url(hass: HomeAssistant, url: str, es5: bool = ...) -> None: ...
def async_remove_panel(
    hass: HomeAssistant, frontend_url_path: str, *, warn_if_unknown: bool = ...
) -> None: ...
def __getattr__(name: str) -> Any: ...
