from collections.abc import Callable, Coroutine, Mapping
from typing import Any

from homeassistant.core import HomeAssistant

class ConfigFlowResult(dict[str, Any]): ...

class ConfigEntry:
    entry_id: str
    options: Mapping[str, Any]
    def add_update_listener(
        self,
        listener: Callable[[HomeAssistant, ConfigEntry], Coroutine[Any, Any, None]],
    ) -> Callable[[], None]: ...
    # Real HA 2026.7 returns None (verified against the 2026.7.3 tag).
    def async_on_unload(self, func: Callable[[], None]) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class ConfigFlow:
    def __init_subclass__(cls, **kwargs: Any) -> None: ...
    def async_abort(self, *, reason: str) -> ConfigFlowResult: ...
    def async_create_entry(self, *, title: str, data: Mapping[str, Any]) -> ConfigFlowResult: ...
    def async_show_form(
        self, *, step_id: str, data_schema: Any = ..., errors: Mapping[str, str] | None = ...
    ) -> ConfigFlowResult: ...
    def _async_current_entries(self) -> list[ConfigEntry]: ...
    def __getattr__(self, name: str) -> Any: ...

class OptionsFlow:
    config_entry: ConfigEntry
    def async_create_entry(self, *, title: str, data: Mapping[str, Any]) -> ConfigFlowResult: ...
    def async_show_form(
        self, *, step_id: str, data_schema: Any = ..., errors: Mapping[str, str] | None = ...
    ) -> ConfigFlowResult: ...
    def __getattr__(self, name: str) -> Any: ...
