from collections.abc import Iterable
from typing import Any

from homeassistant.core import HomeAssistant

class AreaEntry:
    id: str
    name: str
    def __getattr__(self, name: str) -> Any: ...

class AreaRegistry:
    def async_get_area(self, area_id: str) -> AreaEntry | None: ...
    def async_get_area_by_name(self, name: str) -> AreaEntry | None: ...
    def async_list_areas(self) -> Iterable[AreaEntry]: ...
    def __getattr__(self, name: str) -> Any: ...

def async_get(hass: HomeAssistant) -> AreaRegistry: ...
def __getattr__(name: str) -> Any: ...
