from collections.abc import Callable
from typing import Any

def empty_config_schema(domain: str) -> Callable[[Any], Any]: ...
def platform_only_config_schema(domain: str) -> Callable[[Any], Any]: ...
def config_entry_only_config_schema(domain: str) -> Callable[[Any], Any]: ...
def __getattr__(name: str) -> Any: ...
