from typing import Any

from homeassistant.core import HomeAssistant

class Store[T]:
    key: str
    version: int
    def __init__(self, hass: HomeAssistant, version: int, key: str) -> None: ...
    async def async_load(self) -> T | None: ...
    async def async_save(self, data: T) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
